import { Router, type IRouter } from "express";
import healthRouter from "./health";
import statsRouter from "./stats";
import authRouter from "./auth";
import vaultRouter from "./vault";
import projectsRouter from "./projects";
import transactionsRouter from "./transactions";
import reposRouter from "./repos";
import webhookRouter from "./webhook";
import autogitRouter from "./autogit";
import tokensRouter from "./tokens";
import contestRouter from "./contest";
import vaultShortRouter from "./vault-short";
import txShortRouter from "./tx-short";
import x402TestRouter from "./x402-test";
import x402ResultRouter from "./x402-result";
import mcpRouter from "./mcp";
import mcpHermesRouter from "./mcp-hermes";
import copilotRouter from "./copilot";
import groupRouter from "./group";
import publicRouter from "./public";
import rwaRouter from "./rwa";
import openapiRouter from "./openapi";

const router: IRouter = Router();

router.use(healthRouter);
router.use(vaultShortRouter);
router.use(txShortRouter);
router.use(statsRouter);
router.use(tokensRouter);
router.use(authRouter);
router.use(vaultRouter);
router.use(projectsRouter);
router.use(transactionsRouter);
router.use(reposRouter);
router.use(autogitRouter);
router.use(contestRouter);
router.use(x402TestRouter);
router.use(x402ResultRouter);
router.use(mcpRouter);
router.use(mcpHermesRouter);
router.use(copilotRouter);
router.use(groupRouter);
router.use(publicRouter);
router.use(rwaRouter);
router.use(openapiRouter);
router.use(webhookRouter);

export default router;
